---
- hosts: dev
  become: true
  tasks:
    - name: Install python pip
      yum: 
        name: python-pip
        state: present
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: start the container
      docker_container:
        name: java-jsp-diary
        image: "gb443330/java-jsp-diary:{{DOCKER_tag}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
