---
- name: This play is to download the latest war file from nexus
  hosts: localhost
  become: true

  tasks:
     - name: download the war file
       shell: 'curl -u admin:admin -L "http://65.2.169.22:8081/service/rest/v1/search/assets/download?sort=version&repository=java-jsp-diary&maven.groupId=com.yusufsezer&maven.artifactId=java-jsp-diary&maven.extension=war" -H "accept: application/json" --output /home/ansadmin/latest.war'
       args:
          chdir: /home/ansadmin

- name: Deploy the latest war file into apache tomcat
  hosts: tomcat
  become: true

  tasks:
      - copy: 
          src: "{{ item }}"
          dest: "/opt/apache-tomcat-9.0.73/webapps/"
        with_fileglob: 
           - "/home/ansadmin/*.war"
