- hosts: tomcat
  become: true
  vars:
    tomcat_version: 9.0.73
    
    tomcat_permissions_production: False
    
    tomcat_users:
      - username: "tomcat"
        password: "tomcat"
        roles: "manager-gui,manager-script,manager-status,manager-jmx"
      - username: "tomcat2"
        password: "tomcat2"
        roles: "manager-gui"
  roles:
    - role: zaxos.tomcat-ansible-role
